cask-fonts no longer exists
> Error: homebrew/cask-fonts was deprecated. This tap is now
> empty and all its contents were either deleted or migrated.